spring:
  datasource:
    url: jdbc:postgresql://dpg-co1gs80cmk4c73ea1hng-a.frankfurt-postgres.render.com/quizonline_kzkg
    username: fcinar
    password: M5ni7ziqNV0DqcJght57oAht0TeI18CQ
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update